### ISSUE TITLE
发现bug了

### ISSUE THREAD

**Issue by csh159** [seagazer/ccplayer#10]
https://pic.tt.jxnews.com.cn/upload/users/3042349/49ee87a0-9758-11ef-820c-3f73ce8fb93b.mp4?AWSAccessKeyId=9WI18LRJ8XQQ9TPBNQF5&Expires=1730360958&Signature=g7zAHAQHq%2BteSDd8xg%2Fe1%2FetF18%3D

上面的视频在最新版播放不了，而1.0.6的版本可以播放。

**Comment by csh159** [comment]
地址会变，可能上面的地址会访问不了了。

**Comment by csh159** [comment]
![$))( 9INL2OK55%{(L`4@GN](https://github.com/user-attachments/assets/8f326006-f77e-4505-9ba6-6235d9a093af)
1.0.7的高度为0，播放只有声音无画面

**Comment by csh159** [comment]
![RB ZUCSQLZ7P~22%NFHM ~W](https://github.com/user-attachments/assets/e6e8014c-4768-4c6b-9510-7d7391c13350)
高度为0，只有声音，无画面。

**Comment by seagazer** [comment]
> ![RB ZUCSQLZ7P~22%NFHM ~W](https://github.com/user-attachments/assets/e6e8014c-4768-4c6b-9510-7d7391c13350)
> 高度为0，只有声音，无画面。

2666f41f9e3bf5bd8b224d4d00c14aa80b8915cf，这笔代码可能修复了，你可以同步最新代码试试，本周暂时还没有版本更新计划

**Comment by csh159** [comment]
![1730363271909](https://github.com/user-attachments/assets/089720a1-7b6c-4c85-acd0-f09b992c8492)
应该是最新的，打印的还是0

**Comment by seagazer** [comment]
> ![1730363271909](https://github.com/user-attachments/assets/089720a1-7b6c-4c85-acd0-f09b992c8492)
> 应该是最新的，打印的还是0

好的收到，晚点我看下，请问用的src是上面那个链接吗

**Comment by csh159** [comment]
https://pic.tt.jxnews.com.cn/upload/users/3042349/aa5a92f0-975d-11ef-90ec-bfbcc0d481ab.mp4?AWSAccessKeyId=9WI18LRJ8XQQ9TPBNQF5&Expires=1730367221&Signature=cN8Jw1CaExnlYPTDt3yRo523DI8%3D
测试这个地址，也可能会无妨访问，暂时是可用的。

**Comment by seagazer** [comment]
> https://pic.tt.jxnews.com.cn/upload/users/3042349/aa5a92f0-975d-11ef-90ec-bfbcc0d481ab.mp4?AWSAccessKeyId=9WI18LRJ8XQQ9TPBNQF5&Expires=1730367221&Signature=cN8Jw1CaExnlYPTDt3yRo523DI8%3D
> 测试这个地址，也可能会无妨访问，暂时是可用的。

好的，避免失效，如果可以的话麻烦提供一份异常的流程日志

**Comment by seagazer** [comment]
> ![RB ZUCSQLZ7P~22%NFHM ~W](https://github.com/user-attachments/assets/e6e8014c-4768-4c6b-9510-7d7391c13350)
> 高度为0，只有声音，无画面。

测量高度结果为0，我看你截图，大概就是视频宽高比计算那里出错了，视频高度大于宽度那个分支。159行的this.surfaceHeight改成measureHeight，我手动模拟视频参数验证ok了。你可以试试，目前计划本周把pip功能实现后再更新版本。
