### ISSUE TITLE
你好，我想咨询下，咱们播放器可以实现边解密边播放音频资源嘛？还是只能通过提前解密来解决呀

### ISSUE THREAD

**Issue by ksyhsym** [seagazer/ccplayer#11]

**Comment by seagazer** [comment]
> 

目前没有适配验证过这样的业务场景，理论上应该还是要先解密，你也可以尝试下，如有报错可以提供下错误日志，我这边分析下看下后续是否增加该能力

**Comment by ksyhsym** [comment]
明白，感谢感谢，提前解密的话会有解密文件产物，放在内存的话有太大了，我看AVPlayer有个接口是设置 dataSrc：AVDataSrcDescriptor;
这块想问下，如果文件还是存加密的文件，然后设置一个dataSrc，把文件内容读取出来之后，临时解密部分内容然后回传给AVPlayer是不是可以

**Comment by seagazer** [comment]
> 明白，感谢感谢，提前解密的话会有解密文件产物，放在内存的话有太大了，我看AVPlayer有个接口是设置 dataSrc：AVDataSrcDescriptor;
> 这块想问下，如果文件还是存加密的文件，然后设置一个dataSrc，把文件内容读取出来之后，临时解密部分内容然后回传给AVPlayer是不是可以

理论上是的，这接口应该适用于网络下载边缓冲边播放的场景，但是目前我也没验证过这接口的可行性，主要还是难找到相关调试的资源。后续迭代中会增加该类型的source，近期主要在规划音频焦点相关的能力

**Comment by ksyhsym** [comment]
好的好的，感谢大佬~~
