### ISSUE TITLE
切换不等待效果

### ISSUE THREAD

**Issue by Maybe4U** [seagazer/ccplayer#12]
作者你好，想请问下切换不等待，或者说预加载直接播放能指导一下思路吗？感谢！

**Comment by seagazer** [comment]
> 作者你好，想请问下切换不等待，或者说预加载直接播放能指导一下思路吗？感谢！

不知你说的是否类似抖音那种频繁切换视频源的场景，如果是那种场景，可以考虑通过创建多个播放器实例，通过预加载的形式，达到页面展示时能够快速播放的效果。这种实现方式官方其实也有示例，可以参考如下链接：https://developer.huawei.com/consumer/cn/doc/best-practices-V5/bpta-smooth-switching-V5

**Comment by seagazer** [comment]
> 作者你好，想请问下切换不等待，或者说预加载直接播放能指导一下思路吗？感谢！

Swiper配合CcPlayerView的列表播放已增加示例，可参考
