### ISSUE TITLE
无法播放m3u8视频

### ISSUE THREAD

**Issue by mingmingaini** [seagazer/ccplayer#13]
无法播放m3u8视频   如果可以播放麻烦给一个示例感谢

**Comment by seagazer** [comment]
> 无法播放m3u8视频 如果可以播放麻烦给一个示例感谢

播放网络视频，不需要特殊设置，通过MediaSourceFactory构建http的MediaSource即可，并且记得应用添加internet网络权限：
let src = MediaSourceFactory.createUrl('TestM3u8', "https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/hls/xgplayer-demo.m3u8")
this.player.setMediaSource(src, () => {
       this.player.start()
})
如果无法播放，可以通过接口监听error回调，查看具体的报错信息进行分析，例如网络问题，解码失败或者其他
