### ISSUE TITLE
需求：后续是否会集成UI控件面板

### ISSUE THREAD

**Issue by mingmingaini** [seagazer/ccplayer#14]
需求：后续是否会集成UI控件面板

**Comment by seagazer** [comment]
> 需求：后续是否会集成UI控件面板

1.0.5之前的版本其实一直都有预置默认的手势面板UI，但是由于arkui自定义组件扩展能力的局限性太大，灵活性和主流框架有差距，组件内部默认实现的UI很难满足实际的ux设计，实际使用时大部分还是采用自定义UI+绑定事件，因此在后续版本就删除了默认的UI面板
