### ISSUE TITLE
作者你好  请问如何修改请求头中Referer

### ISSUE THREAD

**Issue by 756230883** [seagazer/ccplayer#5]
你好 因为我们的视频链接中加入了 防盗链  如
 http://tv-vod.nbs.cn/vod_storage/vol1/2024/06/06/66615d8489137/66615d848913767849.mp4
会校验请求头中的Referer  请问播放器如何配置Referer 或者将Referer置为空呢 
麻烦作者看一下  谢谢

**Comment by seagazer** [comment]
参照https://github.com/seagazer/ccplayer/issues/4
