### ISSUE TITLE
brightness与控制声音的api过期了，编译不通过。

### ISSUE THREAD

**Issue by csh159** [seagazer/ccplayer#6]

**Comment by seagazer** [comment]
> 

你好，能提供下编译报错的版本信息吗。目前最新版本在oh fullsdk5.0.0.25上编译是通过的

**Comment by csh159** [comment]
开发工具：5.0.3.300
sdk:4.1.0(11)

**Comment by Morzorz** [comment]
版本信息：HarmonyOS NEXT Developer Beta1 SDK, based on OpenHarmony SDK Ohos_sdk_public 5.0.0.25 (API Version 12 Beta1)

**Comment by Morzorz** [comment]
编译报错：1. Cannot find module '@ohos.brightness' or its corresponding type declarations.
2.Property 'setVolume' does not exist on type 'AudioVolumeGroupManager'. Did you mean 'getVolume'?
