### ISSUE TITLE
考不考虑可以切换ijkplayer 的内核

### ISSUE THREAD

**Issue by bingdu0** [seagazer/ccplayer#7]
1.切换ijkplayer 的内核
2.音频播放器能不能后台播放？
3.CcPlayerView 能不能自定义样式

**Comment by seagazer** [comment]
> 1.切换ijkplayer 的内核
> 2.音频播放器能不能后台播放？
> 3.CcPlayerView 能不能自定义样式

1.社区已有对应库，目前不在规划内，后续提供接口，用户可以自己实现解码业务逻辑
2.可以后台播放，参考官方后台任务api，我另一个实验项目listen也可参考
3.目前提供手势操作ui的自定义，详情可以看文档的接口列表和示例工程
