### ISSUE TITLE
修改媒体资源后如何在不播放的情况下获取媒体时长？

### ISSUE THREAD

**Issue by penguin0731** [seagazer/ccplayer#8]

**Comment by seagazer** [comment]
> 

setMediaSource后不调用start即可，只要在prepared状态下都可以获取到媒体时长

**Comment by penguin0731** [comment]
> > 
> 
> setMediaSource后不调用start即可，只要在prepared状态下都可以获取到媒体时长

但是不调用start的话状态没法变成prepared

**Comment by seagazer** [comment]
> > > 
> > 
> > 
> > setMediaSource后不调用start即可，只要在prepared状态下都可以获取到媒体时长
> 
> 但是不调用start的话状态没法变成prepared

dev-5.0分支已经调整了状态机时序，setMediaSource之后会直接进入prepared状态，可以同步下代码

**Comment by seagazer** [comment]
> > > 
> > 
> > setMediaSource后不调用start即可，只要在prepared状态下都可以获取到媒体时长
> 
> 但是不调用start的话状态没法变成prepared

当前如果使用的是ohpm远程依赖，不想播放进行媒体信息的获取，建议可以使用AVMetadataExtractor，5.0分支目前在重构计划中，代码在短期内可能会存在不断的变化

**Comment by penguin0731** [comment]
> > > > 
> > > 
> > > 
> > > setMediaSource后不调用start即可，只要在prepared状态下都可以获取到媒体时长
> > 
> > 
> > 但是不调用start的话状态没法变成prepared
> 
> 当前如果使用的是ohpm远程依赖，不想播放进行媒体信息的获取，建议可以使用AVMetadataExtractor，5.0分支目前在重构计划中，代码在短期内可能会存在不断的变化

好的，谢谢你的建议
