### ISSUE TITLE
有bug,当全屏播放时，视频是横屏的情况，会闪一下在切换到横屏

### ISSUE THREAD

**Issue by csh159** [seagazer/ccplayer#9]

**Comment by csh159** [comment]
请看视频

https://github.com/user-attachments/assets/0e3a472b-2e9f-4f41-95ea-9a0d39732146

**Comment by seagazer** [comment]
> 请看视频
> 
>  WeChat_20241025100104.mp4

你好，从视频上看像是系统回调时序不准，videoSizeChange回调比startRenderFrame后触发，videoSizeChange理论上在prepared时机触发，应该在renderFirstFrame之前应该计算好了宽高比再显示视频画面。目前试了几次本地未复现出来，请问能提供一下机型和对应的日志吗

**Comment by seagazer** [comment]
> 请看视频
> 
>  WeChat_20241025100104.mp4

已复现定位，无需提供日志了。videoSizeChange收到视频宽高参数后，会计算宽高比从而触发XComponent的Surface尺寸变化，此时会触发UI布局（一般一帧16ms），接着系统回调renderFristFrame显示视频画面（与videoSizeChange回调的间隔小于一帧的16ms）。因为surface画面默认是填充组件，当UI布局（耗时）未完成时就会先显示填充的视频画面，然后布局完成后显示设置的宽高比画面，出现画面闪变现象。该问题属于概率问题，只要两次回调间隔时间大于UI布局变更耗时就正常，小于则会出现视频的异常情况。
![image](https://github.com/user-attachments/assets/23941802-4042-4ac5-a5db-4cabdfbf91ec)

**Comment by seagazer** [comment]
感谢反馈，已纳入解决计划，短期内会解决更新

**Comment by seagazer** [comment]
> 请看视频
> 
>  WeChat_20241025100104.mp4

389eee27d980aef7665766f14f4097e201d19c04这笔提交已修复，本地未复现，你可以更新代码试下

**Comment by csh159** [comment]
谢谢，我现在试下

**Comment by csh159** [comment]
经测试正常，谢谢了！
